DROP TABLE IF EXISTS tesisler;

CREATE TABLE tesisler (
    id TEXT PRIMARY KEY,
    "resmiNo" TEXT,
    "firmaAdi" TEXT,
    "tesisAdi" TEXT,
    "ilce" TEXT,
    "tesisSahasi" TEXT,
    "tur" TEXT,
    "kapasite" TEXT,
    "fiiliKapasite" TEXT,
    "finalStatus" TEXT,
    "vkn" TEXT,
    "adres" TEXT,
    "telefon" TEXT,
    "yavruKaynagi" TEXT,
    "tahminiHasat" TEXT,
    "aktifTarih" TEXT,
    "kiraBedel" TEXT,
    "kiraTarih" TEXT,
    "projeKafes" TEXT,
    "mevcutKafes" TEXT,
    "aktifKafesSayisi" TEXT,
    "kafesEbat" TEXT,
    "toplamHacim" TEXT,
    "alan" TEXT,
    "wgs84" TEXT,
    "ed50" TEXT,
    "ialaSamandira" TEXT,
    "ialaBitis" TEXT,
    "vizeTarihi" TEXT,
    "sonDenetim" TEXT,
    "cedKarari" TEXT,
    "suAnalizTarihi" TEXT,
    "tarsim" TEXT,
    "turler" JSONB,
    "sicilGecmisi" JSONB,
    "kaynakSekmeler" JSONB,
    "mergeCount" NUMERIC,
    "_sortDate" TEXT,
    "koordinatList" JSONB,
    "projeKafesList" JSONB,
    "mevcutKafesList" JSONB,
    "personel" TEXT,
    "suKirasi" TEXT,
    "cedDurumu" TEXT,
    "dddUzaklik" TEXT,
    "isDddKapsaminda" BOOLEAN,
    "_devirNotu" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE tesisler ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Herkes gorebilir ve yazabilir tesisler" ON tesisler FOR ALL USING (true);
